In [122]:
import pandas as pd

In [123]:
df_pen_int_fij_x100h = pd.read_csv('../CSV_Cleaned/df_pen_int_fij_x100h_var.csv')

In [124]:
df_pen_int_fij_x100h.head()

,anio_tri,anio,trimestre,provincia,accesos por cada 100 hogares,variacion de los accesos por cada 100 hogares
0,20141,2014,1,Tucumán,33.42,0.0
1,20141,2014,1,Buenos Aires,54.57,0.0
2,20141,2014,1,Capital Federal,112.25,0.0
3,20141,2014,1,Catamarca,24.25,0.0
4,20141,2014,1,Chaco,20.72,0.0

In [125]:
df_pen_int_fij_x100h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 6 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   anio_tri                                       840 non-null    int64
 1   anio                                           840 non-null    int64
 2   trimestre                                      840 non-null    int64
 3   provincia                                      840 non-null    object
 4   accesos por cada 100 hogares                   840 non-null    float64
 5   variacion de los accesos por cada 100 hogares  840 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 39.5+ KB

# Pivot:

##### El pivot table de los accesos por cada100 hogares , denota la participacion de cada provincia en el total del pais, por otra parte teniendo los ingresos acomodados en la misma estructura de tiempos, pero estos ultimos solo a nivel anual... quiere decir que normalizando la tabla 1 y multiplicando por la 2 obtenemos el ingreso monetario que aporto cada provincia por cada acceso cada 100 hogares.

In [126]:
# Hacer la transpuesta o pivot table
df_pivot_df_pen_int_fij_x100h = df_pen_int_fij_x100h.pivot(index='provincia', columns=['anio_tri'], values=['accesos por cada 100 hogares'])

In [127]:
df_pivot_df_pen_int_fij_x100h # agrupado por provincia, accesos x cada 100 h. 24 rows

                    accesos por cada 100 hogares                          \
anio_tri                                   20141   20142   20143   20144
provincia
Buenos Aires                               54.57   55.06   56.75   56.09
Capital Federal                           112.25  113.14  113.80  114.90
Catamarca                                  24.25   24.70   24.71   25.51
Chaco                                      20.72   20.96   21.11   21.87
Chubut                                     41.24   41.41   40.60   40.25
Corrientes                                 22.32   22.58   22.79   23.56
Córdoba                                    52.52   53.45   54.23   54.70
Entre Ríos                                 34.37   34.69   34.98   36.03
Formosa                                    17.42   17.54   17.77   17.96
Jujuy                                      18.42   18.71   18.37   19.60
La Pampa                                   48.43   49.71   55.78   51.27
La Rioja                                   16.29   16.50   16.51   17.01
Mendoza                                    31.91   32.10   32.31   32.64
Misiones                                   23.14   23.37   23.57   24.16
Neuquén                                    49.79   50.84   56.40   52.55
Río Negro                                  44.91   45.33   46.20   45.48
Salta                                      28.70   28.91   29.22   29.53
San Juan                                   27.60   27.78   27.85   28.04
San Luis                                    9.35    9.72    9.71    9.79
Santa Cruz                                 28.94   29.38   28.23   27.80
Santa Fe                                   47.85   48.39   49.20   50.00
Santiago Del Estero                        16.31   16.70   16.49   17.27
Tierra Del Fuego                           63.97   64.36   65.69   66.14
Tucumán                                    33.42   33.94   33.94   35.32

                                                                     ...  \
anio_tri              20151   20152   20153   20154   20161   20162  ...
provincia                                                            ...
Buenos Aires          56.37   56.80   57.69   58.29   57.34   59.34  ...
Capital Federal      114.90  116.07  118.29  118.13  115.16  120.04  ...
Catamarca             25.11   25.45   25.86   26.24   25.91   26.07  ...
Chaco                 26.65   27.46   27.96   28.35   28.08   28.59  ...
Chubut                37.61   36.58   36.81   36.89   36.09   36.12  ...
Corrientes            28.95   29.58   30.17   30.34   30.08   30.58  ...
Córdoba               54.70   55.87   57.08   57.36   55.28   57.55  ...
Entre Ríos            42.07   42.93   43.68   44.11   43.85   44.74  ...
Formosa               18.12   18.36   18.84   19.07   19.04   19.37  ...
Jujuy                 19.69   20.29   21.27   21.47   21.41   21.89  ...
La Pampa              55.51   56.71   57.96   58.76   57.84   60.44  ...
La Rioja              16.70   16.88   17.15   17.32   16.83   16.88  ...
Mendoza               32.37   32.49   32.49   32.49   32.12   32.13  ...
Misiones              26.31   27.35   28.31   28.69   28.37   29.24  ...
Neuquén               51.95   53.12   54.60   58.29   55.75   59.10  ...
Río Negro             45.33   45.98   46.39   46.44   45.84   46.24  ...
Salta                 30.01   30.46   31.18   31.59   31.32   32.08  ...
San Juan              27.55   27.64   27.67   27.66   27.33   27.34  ...
San Luis               9.72    9.71    9.71    9.71    9.59    9.60  ...
Santa Cruz            27.99   27.07   27.61   27.74   26.87   26.73  ...
Santa Fe              50.24   51.18   52.15   52.61   51.28   52.44  ...
Santiago Del Estero   17.06   17.11   17.12   17.00   16.21   15.89  ...
Tierra Del Fuego      74.23   74.51   74.86   66.46   65.83   67.72  ...
Tucumán               35.08   35.69   36.61   37.06   36.72   37.24  ...

                                                                             \
anio_tri              20202   20203   20204   20211   20212   20213   20214
provincia
Buenos Aires          65.22   67.66   68.98   69.11   70.00   71.68   75.66
Capital Federal      106.41  107.68  108.31  108.42  110.14  111.27  111.27
Catamarca             45.43   47.16   49.41   48.90   52.34   52.71   55.25
Chaco                 39.83   41.54   43.03   43.14   43.33   42.96   44.05
Chubut                57.34   68.34   68.35   68.99   72.29   80.71   82.57
Corrientes            40.30   41.75   42.43   42.66   43.54   44.90   45.51
Córdoba               72.71   75.22   78.08   78.59   80.12   81.28   84.51
Entre Ríos            56.54   58.19   59.47   60.44   61.66   62.18   63.16
Formosa               31.14   31.91   32.49   32.73   33.23   33.96   34.45
Jujuy                 47.89   54.04   53.46   55.63   56.18   55.69   56.92
La Pampa              76.10   79.26   81.77   81.78   82.08   84.28   89.57
La Rioja              49.84   50.12   50.11   49.81   76.98   77.26   77.92
Mendoza               36.25   37.35   38.63   39.15   40.97   45.55   47.51
Misiones              40.89   41.60   42.64   43.17   45.01   45.57   49.06
Neuquén               63.90   65.24   67.00   66.84   69.14   69.71   73.30
Río Negro             56.37   57.05   61.09   60.88   61.94   61.97   65.69
Salta                 51.58   52.32   54.04   53.93   54.93   55.96   56.81
San Juan              35.09   38.79   36.32   39.06   39.28   39.46   39.59
San Luis              78.41   79.96   81.68   81.24   83.48   79.87   80.30
Santa Cruz            35.79   35.95   37.00   41.65   44.01   43.75   43.05
Santa Fe              70.00   72.12   73.58   73.92   75.07   75.02   77.09
Santiago Del Estero   43.47   43.38   43.75   45.67   46.56   47.00   47.05
Tierra Del Fuego      76.37   76.81   76.27   77.35   67.89   94.95   98.40
Tucumán               51.78   53.23   54.78   54.82   54.93   54.64   55.93


anio_tri              20221   20222   20223
provincia
Buenos Aires          76.08   77.58   78.11
Capital Federal      111.80  121.31  122.28
Catamarca             58.21   62.40   65.33
Chaco                 44.06   43.79   43.86
Chubut                88.05   83.19   84.38
Corrientes            47.64   48.35   48.21
Córdoba               85.76   87.48   88.31
Entre Ríos            63.70   63.90   63.67
Formosa               34.96   43.42   43.76
Jujuy                 58.06   57.32   58.91
La Pampa              91.66   92.98   96.59
La Rioja              78.77   80.14   80.66
Mendoza               48.74   49.39   51.03
Misiones              49.04   51.00   51.82
Neuquén               74.17   80.02   80.37
Río Negro             67.04   67.85   67.98
Salta                 56.11   57.54   57.76
San Juan              43.55   49.46   50.80
San Luis              80.72   81.76   81.74
Santa Cruz            43.34   43.15   43.19
Santa Fe              77.30   77.90   78.55
Santiago Del Estero   47.17   47.70   47.98
Tierra Del Fuego      98.29   99.86   99.51
Tucumán               57.39   59.31   61.14

[24 rows x 35 columns]

In [128]:
from sklearn.preprocessing import normalize

# Normalizar el DataFrame
df_normalized_df_pivot_df_pen_int_fij_x100h = normalize(df_pivot_df_pen_int_fij_x100h, axis=1)

# Crear un nuevo DataFrame con los datos normalizados y las mismas columnas e índices
df_normalized_df_pivot_df_pen_int_fij_x100h = pd.DataFrame(df_normalized_df_pivot_df_pen_int_fij_x100h, columns=df_pivot_df_pen_int_fij_x100h.columns, index=df_pivot_df_pen_int_fij_x100h.index)

In [129]:
df_normalized_df_pivot_df_pen_int_fij_x100h.head(5)

                accesos por cada 100 hogares                                \
anio_tri                               20141     20142     20143     20144
provincia
Buenos Aires                        0.144313  0.145609  0.150078  0.148333
Capital Federal                     0.167144  0.168470  0.169452  0.171090
Catamarca                           0.108079  0.110084  0.110129  0.113694
Chaco                               0.103081  0.104275  0.105021  0.108802
Chubut                              0.127336  0.127861  0.125360  0.124279

                                                                             \
anio_tri            20151     20152     20153     20154     20161     20162
provincia
Buenos Aires     0.149073  0.150210  0.152564  0.154151  0.151638  0.156928
Capital Federal  0.171090  0.172833  0.176138  0.175900  0.171477  0.178744
Catamarca        0.111912  0.113427  0.115254  0.116948  0.115477  0.116190
Chaco            0.132582  0.136612  0.139100  0.141040  0.139697  0.142234
Chubut           0.116128  0.112947  0.113658  0.113905  0.111434  0.111527

                 ...                                                    \
anio_tri         ...     20202     20203     20204     20211     20212
provincia        ...
Buenos Aires     ...  0.172478  0.178930  0.182421  0.182765  0.185118
Capital Federal  ...  0.158448  0.160339  0.161278  0.161441  0.164003
Catamarca        ...  0.202475  0.210185  0.220213  0.217940  0.233272
Chaco            ...  0.198152  0.206660  0.214072  0.214619  0.215565
Chubut           ...  0.177048  0.211012  0.211043  0.213019  0.223208


anio_tri            20213     20214     20221     20222     20223
provincia
Buenos Aires     0.189561  0.200087  0.201197  0.205164  0.206566
Capital Federal  0.165685  0.165685  0.166474  0.180635  0.182079
Catamarca        0.234921  0.246241  0.259434  0.278108  0.291166
Chaco            0.213724  0.219147  0.219196  0.217853  0.218201
Chubut           0.249207  0.254950  0.271870  0.256864  0.260538

[5 rows x 35 columns]

In [130]:
# Revertir la tabla pivotada
df_pivot_df_pen_int_fij_x100h_normalized_revertido = df_normalized_df_pivot_df_pen_int_fij_x100h.stack().reset_index()
df_pivot_df_pen_int_fij_x100h_normalized_revertido.columns = ['provincia', 'anio_tri', 'accesos por cada 100 hogares']

df_pivot_df_pen_int_fij_x100h_normalized_revertido

        provincia  anio_tri  accesos por cada 100 hogares
0    Buenos Aires     20141                      0.144313
1    Buenos Aires     20142                      0.145609
2    Buenos Aires     20143                      0.150078
3    Buenos Aires     20144                      0.148333
4    Buenos Aires     20151                      0.149073
..            ...       ...                           ...
835       Tucumán     20213                      0.207818
836       Tucumán     20214                      0.212724
837       Tucumán     20221                      0.218277
838       Tucumán     20222                      0.225580
839       Tucumán     20223                      0.232540

[840 rows x 3 columns]

___________________________________________________________________________________________________________________

#### pivot de variacion de los accesos x cada 100 hogares:

In [131]:
df_pivot_df_pen_int_fij_x100h_var = df_pen_int_fij_x100h.pivot(index='provincia', columns=['anio_tri'], values=['variacion de los accesos por cada 100 hogares'])

In [132]:
df_pivot_df_pen_int_fij_x100h_var.head(5)

                variacion de los accesos por cada 100 hogares            \
anio_tri                                                20141     20142
provincia
Buenos Aires                                              0.0  0.008979
Capital Federal                                           0.0  0.007929
Catamarca                                                 0.0  0.018557
Chaco                                                     0.0  0.011583
Chubut                                                    0.0  0.004122

                                                                             \
anio_tri            20143     20144     20151     20152     20153     20154
provincia
Buenos Aires     0.030694 -0.011630  0.004992  0.007628  0.015669  0.010400
Capital Federal  0.005833  0.009666  0.000000  0.010183  0.019126 -0.001353
Catamarca        0.000405  0.032376 -0.015680  0.013540  0.016110  0.014695
Chaco            0.007156  0.036002  0.218564  0.030394  0.018208  0.013948
Chubut          -0.019560 -0.008621 -0.065590 -0.027386  0.006288  0.002173

                                     ...                                \
anio_tri            20161     20162  ...     20202     20203     20204
provincia                            ...
Buenos Aires    -0.016298  0.034880  ...  0.013835  0.037412  0.019509
Capital Federal -0.025142  0.042376  ...  0.004057  0.011935  0.005851
Catamarca       -0.012576  0.006175  ...  0.207602  0.038081  0.047710
Chaco           -0.009524  0.018162  ...  0.062700  0.042932  0.035869
Chubut          -0.021686  0.000831  ...  0.118393  0.191838  0.000146

                                                                             \
anio_tri            20211     20212     20213     20214     20221     20222
provincia
Buenos Aires     0.001885  0.012878  0.024000  0.055525  0.005551  0.019716
Capital Federal  0.001016  0.015864  0.010260  0.000000  0.004763  0.085063
Catamarca       -0.010322  0.070348  0.007069  0.048188  0.053575  0.071981
Chaco            0.002556  0.004404 -0.008539  0.025372  0.000227 -0.006128
Chubut           0.009364  0.047833  0.116475  0.023045  0.066368 -0.055196


anio_tri            20223
provincia
Buenos Aires     0.006832
Capital Federal  0.007996
Catamarca        0.046955
Chaco            0.001599
Chubut           0.014305

[5 rows x 35 columns]

# _____________________________________________________________________________________________________________________

# Combinado con los ingresos por año...

In [133]:
df_ingresos_inter_fijo_var = pd.read_csv('../CSV_Cleaned/df_ingresos_inter_fijo_var')

In [134]:
df_ingresos_inter_fijo_var.head(5)

,anio_tri,anio,trimestre,variacion trimestral ingresos (miles de pesos),ingresos (miles de pesos),periodo
0,20141,2014,1,NaN,2984054,Ene-Mar 2014
1,20142,2014,2,0.096098,3270816,Abr-Jun 2014
2,20143,2014,3,0.063538,3478638,Jul-Sept 2014
3,20144,2014,4,0.135629,3950441,Oct-Dic 2014
4,20151,2015,1,0.234390,4876385,Ene-Mar 2015

# df_pivot:

In [135]:
df_pivot_df_ingresos_inter_fijo = df_ingresos_inter_fijo_var.pivot(index='anio_tri', columns=['anio','trimestre'], values=['ingresos (miles de pesos)'])

In [136]:
df_pivot_df_ingresos_inter_fijo.head(5)

          ingresos (miles de pesos)                                   \
anio                           2014
trimestre                         1          2          3          4
anio_tri
20141                     2984054.0        NaN        NaN        NaN
20142                           NaN  3270816.0        NaN        NaN
20143                           NaN        NaN  3478638.0        NaN
20144                           NaN        NaN        NaN  3950441.0
20151                           NaN        NaN        NaN        NaN

                                           ...                                \
anio            2015             2016      ... 2020         2021
trimestre          1   2   3   4    1   2  ...    2   3   4    1   2   3   4
anio_tri                                   ...
20141            NaN NaN NaN NaN  NaN NaN  ...  NaN NaN NaN  NaN NaN NaN NaN
20142            NaN NaN NaN NaN  NaN NaN  ...  NaN NaN NaN  NaN NaN NaN NaN
20143            NaN NaN NaN NaN  NaN NaN  ...  NaN NaN NaN  NaN NaN NaN NaN
20144            NaN NaN NaN NaN  NaN NaN  ...  NaN NaN NaN  NaN NaN NaN NaN
20151      4876385.0 NaN NaN NaN  NaN NaN  ...  NaN NaN NaN  NaN NaN NaN NaN


anio      2022
trimestre    1   2   3
anio_tri
20141      NaN NaN NaN
20142      NaN NaN NaN
20143      NaN NaN NaN
20144      NaN NaN NaN
20151      NaN NaN NaN

[5 rows x 35 columns]

In [137]:
df_pivot_df_ingresos_inter_fijo.fillna(0)

          ingresos (miles de pesos)                                   \
anio                           2014
trimestre                         1          2          3          4
anio_tri
20141                     2984054.0        0.0        0.0        0.0
20142                           0.0  3270816.0        0.0        0.0
20143                           0.0        0.0  3478638.0        0.0
20144                           0.0        0.0        0.0  3950441.0
20151                           0.0        0.0        0.0        0.0
20152                           0.0        0.0        0.0        0.0
20153                           0.0        0.0        0.0        0.0
20154                           0.0        0.0        0.0        0.0
20161                           0.0        0.0        0.0        0.0
20162                           0.0        0.0        0.0        0.0
20163                           0.0        0.0        0.0        0.0
20164                           0.0        0.0        0.0        0.0
20171                           0.0        0.0        0.0        0.0
20172                           0.0        0.0        0.0        0.0
20173                           0.0        0.0        0.0        0.0
20174                           0.0        0.0        0.0        0.0
20181                           0.0        0.0        0.0        0.0
20182                           0.0        0.0        0.0        0.0
20183                           0.0        0.0        0.0        0.0
20184                           0.0        0.0        0.0        0.0
20191                           0.0        0.0        0.0        0.0
20192                           0.0        0.0        0.0        0.0
20193                           0.0        0.0        0.0        0.0
20194                           0.0        0.0        0.0        0.0
20201                           0.0        0.0        0.0        0.0
20202                           0.0        0.0        0.0        0.0
20203                           0.0        0.0        0.0        0.0
20204                           0.0        0.0        0.0        0.0
20211                           0.0        0.0        0.0        0.0
20212                           0.0        0.0        0.0        0.0
20213                           0.0        0.0        0.0        0.0
20214                           0.0        0.0        0.0        0.0
20221                           0.0        0.0        0.0        0.0
20222                           0.0        0.0        0.0        0.0
20223                           0.0        0.0        0.0        0.0

                                                                             \
anio            2015                                        2016
trimestre          1          2          3          4          1          2
anio_tri
20141            0.0        0.0        0.0        0.0        0.0        0.0
20142            0.0        0.0        0.0        0.0        0.0        0.0
20143            0.0        0.0        0.0        0.0        0.0        0.0
20144            0.0        0.0        0.0        0.0        0.0        0.0
20151      4876385.0        0.0        0.0        0.0        0.0        0.0
20152            0.0  4701791.0        0.0        0.0        0.0        0.0
20153            0.0        0.0  5153739.0        0.0        0.0        0.0
20154            0.0        0.0        0.0  5376899.0        0.0        0.0
20161            0.0        0.0        0.0        0.0  5936845.0        0.0
20162            0.0        0.0        0.0        0.0        0.0  6534241.0
20163            0.0        0.0        0.0        0.0        0.0        0.0
20164            0.0        0.0        0.0        0.0        0.0        0.0
20171            0.0        0.0        0.0        0.0        0.0        0.0
20172            0.0        0.0        0.0        0.0        0.0        0.0
20173            0.0        0.0        0.0        0.0        0.0        0.0
20174            0.0        0.0        0.0        0.0        0.0        0.0
20181            0.0        0.0        0.0        0.0        0.0        0.0
20182            0.0        0.0        0.0        0.0        0.0        0.0
20183            0.0        0.0        0.0        0.0        0.0        0.0
20184            0.0        0.0        0.0        0.0        0.0        0.0
20191            0.0        0.0        0.0        0.0        0.0        0.0
20192            0.0        0.0        0.0        0.0        0.0        0.0
20193            0.0        0.0        0.0        0.0        0.0        0.0
20194            0.0        0.0        0.0        0.0        0.0        0.0
20201            0.0        0.0        0.0        0.0        0.0        0.0
20202            0.0        0.0        0.0        0.0        0.0        0.0
20203            0.0        0.0        0.0        0.0        0.0        0.0
20204            0.0        0.0        0.0        0.0        0.0        0.0
20211            0.0        0.0        0.0        0.0        0.0        0.0
20212            0.0        0.0        0.0        0.0        0.0        0.0
20213            0.0        0.0        0.0        0.0        0.0        0.0
20214            0.0        0.0        0.0        0.0        0.0        0.0
20221            0.0        0.0        0.0        0.0        0.0        0.0
20222            0.0        0.0        0.0        0.0        0.0        0.0
20223            0.0        0.0        0.0        0.0        0.0        0.0

           ...                                                              \
anio       ...        2020                                2021
trimestre  ...           2           3           4           1           2
anio_tri   ...
20141      ...         0.0         0.0         0.0         0.0         0.0
20142      ...         0.0         0.0         0.0         0.0         0.0
20143      ...         0.0         0.0         0.0         0.0         0.0
20144      ...         0.0         0.0         0.0         0.0         0.0
20151      ...         0.0         0.0         0.0         0.0         0.0
20152      ...         0.0         0.0         0.0         0.0         0.0
20153      ...         0.0         0.0         0.0         0.0         0.0
20154      ...         0.0         0.0         0.0         0.0         0.0
20161      ...         0.0         0.0         0.0         0.0         0.0
20162      ...         0.0         0.0         0.0         0.0         0.0
20163      ...         0.0         0.0         0.0         0.0         0.0
20164      ...         0.0         0.0         0.0         0.0         0.0
20171      ...         0.0         0.0         0.0         0.0         0.0
20172      ...         0.0         0.0         0.0         0.0         0.0
20173      ...         0.0         0.0         0.0         0.0         0.0
20174      ...         0.0         0.0         0.0         0.0         0.0
20181      ...         0.0         0.0         0.0         0.0         0.0
20182      ...         0.0         0.0         0.0         0.0         0.0
20183      ...         0.0         0.0         0.0         0.0         0.0
20184      ...         0.0         0.0         0.0         0.0         0.0
20191      ...         0.0         0.0         0.0         0.0         0.0
20192      ...         0.0         0.0         0.0         0.0         0.0
20193      ...         0.0         0.0         0.0         0.0         0.0
20194      ...         0.0         0.0         0.0         0.0         0.0
20201      ...         0.0         0.0         0.0         0.0         0.0
20202      ...  32102476.0         0.0         0.0         0.0         0.0
20203      ...         0.0  31997445.0         0.0         0.0         0.0
20204      ...         0.0         0.0  33539703.0         0.0         0.0
20211      ...         0.0         0.0         0.0  36676371.0         0.0
20212      ...         0.0         0.0         0.0         0.0  38239667.0
20213      ...         0.0         0.0         0.0         0.0         0.0
20214      ...         0.0         0.0         0.0         0.0         0.0
20221      ...         0.0         0.0         0.0         0.0         0.0
20222      ...         0.0         0.0         0.0         0.0         0.0
20223      ...         0.0         0.0         0.0         0.0         0.0


anio                                     2022
trimestre           3           4           1           2           3
anio_tri
20141             0.0         0.0         0.0         0.0         0.0
20142             0.0         0.0         0.0         0.0         0.0
20143             0.0         0.0         0.0         0.0         0.0
20144             0.0         0.0         0.0         0.0         0.0
20151             0.0         0.0         0.0         0.0         0.0
20152             0.0         0.0         0.0         0.0         0.0
20153             0.0         0.0         0.0         0.0         0.0
20154             0.0         0.0         0.0         0.0         0.0
20161             0.0         0.0         0.0         0.0         0.0
20162             0.0         0.0         0.0         0.0         0.0
20163             0.0         0.0         0.0         0.0         0.0
20164             0.0         0.0         0.0         0.0         0.0
20171             0.0         0.0         0.0         0.0         0.0
20172             0.0         0.0         0.0         0.0         0.0
20173             0.0         0.0         0.0         0.0         0.0
20174             0.0         0.0         0.0         0.0         0.0
20181             0.0         0.0         0.0         0.0         0.0
20182             0.0         0.0         0.0         0.0         0.0
20183             0.0         0.0         0.0         0.0         0.0
20184             0.0         0.0         0.0         0.0         0.0
20191             0.0         0.0         0.0         0.0         0.0
20192             0.0         0.0         0.0         0.0         0.0
20193             0.0         0.0         0.0         0.0         0.0
20194             0.0         0.0         0.0         0.0         0.0
20201             0.0         0.0         0.0         0.0         0.0
20202             0.0         0.0         0.0         0.0         0.0
20203             0.0         0.0         0.0         0.0         0.0
20204             0.0         0.0         0.0         0.0         0.0
20211             0.0         0.0         0.0         0.0         0.0
20212             0.0         0.0         0.0         0.0         0.0
20213      42999944.0         0.0         0.0         0.0         0.0
20214             0.0  45467887.0         0.0         0.0         0.0
20221             0.0         0.0  55589997.0         0.0         0.0
20222             0.0         0.0         0.0  60335724.0         0.0
20223             0.0         0.0         0.0         0.0  67055930.0

[35 rows x 35 columns]

¿Tengo que, de alguna forma implementar el mismo índice? Para ambos datos prima, antes de multiplicarlos. La otra opción que se me ocurre es separar los datos. Y multiplicarlos, y luego ponerle los encabezados que necesito. Pero bueno, me voy a bañar.