In [12]:
import pandas as pd

In [13]:
df_rangos_de_vel = pd.read_csv('../CSV data importada/CSV Accesos a internet/Acceso a Internet Fijo por rangos de velocidad de bajada y provincia.csv',encoding='UTF-8',sep=',',thousands='.')

In [14]:
df_rangos_de_vel

,Año,Trimestre,Provincia,HASTA 512 kbps,+ 512 Kbps - 1 Mbps,+ 1 Mbps - 6 Mbps,+ 6 Mbps - 10 Mbps,+ 10 Mbps - 20 Mbps,+ 20 Mbps - 30 Mbps,+ 30 Mbps,OTROS,Total
0,2022,3,Buenos Aires,29985,27709,290315,297915,267044,124190,3618689,65821.0,4721668
1,2022,3,Capital Federal,517,5742,34371,67829,51946,28692,1253105,105477.0,1547679
2,2022,3,Catamarca,71,384,3107,5389,5099,3737,50298,2208.0,70293
3,2022,3,Chaco,461,987,16782,18938,8049,15828,79390,3711.0,144146
4,2022,3,Chubut,109,1444,45707,30940,34682,15309,17563,20024.0,165778
...,...,...,...,...,...,...,...,...,...,...,...,...
835,2014,1,Santa Cruz,161,1625,24972,1,1,0,0,0.0,26760
836,2014,1,Santa Fe,8456,124468,345225,20328,6845,23,668,0.0,506013
837,2014,1,Santiago Del Estero,1234,10531,22817,2422,109,0,0,0.0,37113
838,2014,1,Tierra Del Fuego,12,607,30902,6,0,0,0,0.0,31527
839,2014,1,Tucumán,6,34672,83210,11779,362,3,0,0.0,130032

In [21]:
df_rangos_de_vel = df_rangos_de_vel.fillna(0)
df_rangos_de_vel['OTROS'] = df_rangos_de_vel['OTROS'].astype('Int64')

In [22]:
df_rangos_de_vel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Año                  840 non-null    int64
 1   Trimestre            840 non-null    int64
 2   Provincia            840 non-null    object
 3   HASTA 512 kbps       840 non-null    int64
 4   + 512 Kbps - 1 Mbps  840 non-null    int64
 5   + 1 Mbps - 6 Mbps    840 non-null    int64
 6   + 6 Mbps - 10 Mbps   840 non-null    int64
 7   + 10 Mbps - 20 Mbps  840 non-null    int64
 8   + 20 Mbps - 30 Mbps  840 non-null    int64
 9   + 30 Mbps            840 non-null    int64
 10  OTROS                840 non-null    Int64
 11  Total                840 non-null    int64
dtypes: Int64(1), int64(10), object(1)
memory usage: 79.7+ KB